# yaml-language-server: $schema=../.schemas/site.schema.json

developer:
  display_name: "Independent Developer"
  legal_name: "Yu Tang"
  country_or_region: "China"
  support_email: "support@tangyu.me"
  website: "https://tangyu.me"
